programs/Question13.java
programs/Question14.java

Question 13 added in JAVA

---

programs/question21.java

added java  program for question 21

added java  program for question 21

---

programs/Question100.java
programs/Question99.java

Question 100 added

---

programs/Question27.java

updated code for question 27

---

programs/Question32.java

Added question 32
- How to add two matrix in java program

Added question32

---

programs/Question25.java

added code for Question-25

---

programs/Question-20.java

Contribute towards hacktoberfest-2022. Please add this repository label as hacktoberfest-accepted. Thank you.

Program of reverse the number by user input in java

---

programs/check whether installed on cpmputer.java

Hello Folks ,
please merge the PR.
and make the new java program  check whether Java is installed on your computer.
thanks

Create check whether installed on computer.java

---

programs/Calcultor Basic.java

Hey Folks,
merging the PR basic calcultor using java program.

Create Calcultor Basic.java

---

programs/Question-3.java
programs/que-4.java

Hie I' ve  uploaded the code of Question 3.

create Question -3

---

programs/Question-62.java

Contributing Towards Hacktoberfest-2022. Please add this repository to the hacktoberfest-accepted label or create mearge on this. It's humble request. Thank You.

Bubble sort Program in java Question-62

---

programs/Question-42.java

Question 42

---

programs/Question94.java

java code solving Question 94.

Question94.java

---

programs/Question47.java

Java code solving question 47, create a constructor.

Question47.java

---

programs/BubbleSort.java

Hello, added a bubble sort algorithm in a simplified manner.
If it follows the acceptance rule please merge the PR under hacktoberfest accepted label.
Thanks

Added BubbleSort.java file

---

programs/InsertionSort.java

Hello, added a program of insertion sort algorithm in java.
If it follows the acceptance criteria please merge the PR under hacktoberfest-accepted label.
Thanks

Added InsertionSort.java file

---

programs/Question-97.java

added code for question 97 - How to create Array program in java

Question-97.java

---

programs/question_13.java

Java program to check if the number is odd or even.

solved Question 13/100

---

programs/Question48.java

Q.48 How to create constructor overloading in java Program

Added solution to Question 48

---

programs/Question80.java

Q.80 How to convert string to integer in java program

Added solution to question 80

---

programs/Question52.java

Q.52 How to create Interface in java Program

Added solution to Question 52

---

python/Guess The number.py

Guess the number program has been created in python

Guess The number game
